name: Render Quarto Document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  render_quarto:
    runs-on: macos-latest
    strategy:
      matrix:
      r-version: ['3.6.3', '4.3.3']

    steps:
      - uses: actions/checkout@v4
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Render Quarto
        run: |
          quarto render steinschlag_bericht.qmd --to pdf
        shell: bash
        
