name: Render Quarto Document

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Quarto
      run: |
        R -e 'install.packages("quarto")'
        R -e 'quarto::install_dependencies()'
        
    - name: Render Quarto document
      run: |
        R -e 'quarto::render("steinschlag_bericht.qmd")'
