name: Render Quarto Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render_quarto:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.3.3'

    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc pandoc-citeproc texlive texlive-latex-extra
        Rscript -e "install.packages('renv')"

    - name: Restore renv environment
      run: Rscript -e 'renv::restore()'

    - name: Render Quarto to PDF
      run: Rscript -e 'quarto::render("steinschlag_bericht.qmd", output_format = "pdf")'
